### ISSUE TITLE
Thanks for the great package!

### ISSUE THREAD

**Issue by nohli** [VictorKachalov/health_kit_reporter#12]
I was waiting for a package like yours. Yesterday, I've implemented saving mindful minutes and it works well!

If interested, I could share some sample code here, that works for this use case (was struggling before finding out that I had to use Category() and that CategoryHarmonized.value needed to be 0 - also found out that most of the values for Device are better left null).

FYI, in the Swift package, there is a typo in the error messages ('foramtted').

**Comment by VictorKachalov** [comment]
Hi @nohli ,

thank for your kind words, I am glad that this package helped you.

I am sorry beforhand, if I misunderstand your issue about 0 values and null for Device...
You mean you don't receive any information about device and 0 value when you try to fetch Category types? 
Have you tried to use it native with my original native [Pod](https://cocoapods.org/pods/HealthKitReporter) ? 

Do you receive the same result if you try to implement it natively?

P.S thank for your notice about the type (have fixed)

**Comment by nohli** [comment]
Hey, @VictorKachalov this is not an issue - just wanted to say thanks and offer example code for saving to mindful minutes.

CategoryHarmonized.value must be 0 for mindful minutes - otherwise the app exits (crashes) without an error (had to run the app from Xcode to see the reason).
And the Device() arguments are not necessary, so can be set to null. (just saying for other users, as there is no documentation yet).

```
    const CategoryHarmonized harmonized = CategoryHarmonized(
      0,
      'Meditation',
      <String, dynamic>{'': ''},
    );
    final Category mindfulMinutes = Category(
      CategoryType.mindfulSession.identifier,
      start.millisecondsSinceEpoch,
      endTime.millisecondsSinceEpoch,
      device,
      sourceRevision,
      harmonized,
    );
    HealthKitReporter.save(mindfulMinutes);
```

**Comment by ollydixon** [comment]
Getting a crash for the following, and not sure why.

```
      final started = DateTime.parse(drill.timeStartedISO!);
      final ended = DateTime.parse(drill.timeEndedISO!);

      final packageInfo = await PackageInfo.fromPlatform();

      final operatingSystem = OperatingSystem(1, 2, 3);
      final source = Source(packageInfo.appName, packageInfo.packageName);
      final sourceRevision = SourceRevision(source, null, null, '4', operatingSystem);

      final harmonized = QuantityHarmonized(
        drill.totalCalories().round(),
        'CALORIES',
        {
          'Total Weight Lifted': drill.getTotalLoggedVolumeKG(),
          'Workouts': drill.getWorkoutsDone(),
          'Workout Name': drill.makeupName(),
        },
      );

      final steps = Quantity(
        drill.uid,
        QuantityType.activeEnergyBurned.identifier,
        started.millisecondsSinceEpoch,
        ended.millisecondsSinceEpoch,
        null,
        sourceRevision,
        harmonized,
      );

      await HealthKitReporter.save(steps);
```
