### ISSUE TITLE
Reading workouts always returns empty array

### ISSUE THREAD

**Issue by SamBergeron** [VictorKachalov/health_kit_reporter#15]
**Describe the bug**
Reading data from any quantityQuery will return the appropriate information, but trying to read workout information with a `workoutQuery` will always return an empty array. Read permissions are definitely enabled.

Sample code for reading: 
```
final canReadWorkouts = await HealthKitReporter.requestAuthorization(
            [WorkoutType.workoutType.identifier], []);
        if (canReadWorkouts) {
          final workouts = await HealthKitReporter.workoutQuery(predicate);
          _logger.info("Workouts: ${workouts.length}");
          for (var workout in workouts) {
            _logger.info(
                "workout: ${workout.harmonized.value} ${workout.harmonized.totalEnergyBurnedUnit}");
          }
        }
``` 
Will return `Workouts: 0`

`predicate` for the same time period appropriately fetches active energy quantity

AH has a couple workouts logged
![Screen Shot 2021-02-19 at 3 17 56 PM](https://user-images.githubusercontent.com/3879294/108571759-bb370100-72c5-11eb-81c3-34faedd01a41.png)

I'm wondering if I'm pulling the workouts properly or if I'm missing a permission. 
Any extra info would be appreciated.

**Comment by VictorKachalov** [comment]
Hi @SamBergeron 

Please check out new version 1.1.0 (it includes your changes from original reporter)
