### ISSUE TITLE
Remove android from supported platforms in pubspec.yaml

### ISSUE THREAD

**Issue by mjstel** [VictorKachalov/health_kit_reporter#19]
### The problem
Since this plugin is obviously not supported by the Android platform, it is confusing, that you still find this package on pub.dev when  you are filtering for Android packages. 

### The solution
You just could remove remove the platform from the pubspec.yaml and drop the android folder. The drawback is, that the package is losing 10 pub points, but i think this should be done.

**Comment by VictorKachalov** [comment]
Please check new version 1.3.0. The android support removed
