### ISSUE TITLE
Cannot run example app

### ISSUE THREAD

**Issue by spiritinlife** [VictorKachalov/health_kit_reporter#2]
**Describe the bug**
Cannot run example app. It breaks with a couple of swift compiler errors.
For instance `Use of undeclared type 'Harmonized'` and `Use of undeclared type 'HKElectrocardiogram'`

**Additional context**
Tested with flutter 1.20 and 1.22

**Comment by VictorKachalov** [comment]
Was not able to reproduce the issue with crashing. 
Tried to launch from Xcode 12.2 and from IntelliJ 2020.2.

Added an example how to read Electrocardiograms. (HKElectrocardiogram works only with iOS 14 and higher https://github.com/VictorKachalov/health_kit_reporter#requirements)

Please try version 1.0.2. [pub.dev](https://pub.dev/packages/health_kit_reporter )

**Comment by spiritinlife** [comment]
Hey @VictorKachalov thank you for your help.

I am using 1.0.2 but xcode is at 11.5. I am going to update xcode soon, to see if it resolves the issue.

**Comment by spiritinlife** [comment]
@VictorKachalov Didn't get the chance to download latest xcode, but a colleague of mine managed to execute your example with the latest xcode.

So the issue i see, is related to my environment.
