### ISSUE TITLE
App crashes, no reason why.

### ISSUE THREAD

**Issue by ollydixon** [VictorKachalov/health_kit_reporter#23]
The app just closes; no reason why.

```
      final started = DateTime.parse(drill.timeStartedISO!);
      final ended = DateTime.parse(drill.timeEndedISO!);

      final packageInfo = await PackageInfo.fromPlatform();

      final operatingSystem = OperatingSystem(1, 2, 3);
      final source = Source(packageInfo.appName, packageInfo.packageName);
      final sourceRevision = SourceRevision(source, null, null, '4', operatingSystem);

      final harmonized = QuantityHarmonized(
        drill.totalCalories().round(),
        'CALORIES',
        {
          'Total Weight Lifted': drill.getTotalLoggedVolumeKG(),
          'Workouts': drill.getWorkoutsDone(),
          'Workout Name': drill.makeupName(),
        },
      );

      final steps = Quantity(
        drill.uid,
        QuantityType.activeEnergyBurned.identifier,
        started.millisecondsSinceEpoch,
        ended.millisecondsSinceEpoch,
        null,
        sourceRevision,
        harmonized,
      );

      await HealthKitReporter.save(steps);
```

**Comment by VictorKachalov** [comment]
Hi @ollydixon 

Thank you for your report. According to Code I see that the unit for calories should be selected as Apple provides https://developer.apple.com/documentation/healthkit/hkunit/1615733-init/

You could use "kcal", should fix the issue

Also I would suggest to try to launch the app via Xcode sometimes as well... The reason behind is that the tricky HKUnit contstructor does not throw any error which can be caught and sent to Flutter Channel

**Comment by ollydixon** [comment]
@VictorKachalov thanks; would be nice to see some docs for that. This package is extremely difficuit to implement hehe. :-D maybe some consts would be good?

**Comment by VictorKachalov** [comment]
> @VictorKachalov thanks; would be nice to see some docs for that. This package is extremely difficuit to implement hehe. :-D maybe some consts would be good?

I agree with consts. It will be take a lot of time though to create all of them for SI and Imperial units :) 

In the documentation, I recomend to use "preferredUnits" function. It is quite handy to maintain and not operate with strings manually. You can see how it is implemented inside the example, line 453, the function name "void handleQuantitiySamples()"
