### ISSUE TITLE
Is it possible to get separate characteristics?

### ISSUE THREAD

**Issue by AlexanderZgersky** [VictorKachalov/health_kit_reporter#29]
I have to get **BirthDate** and **BiologicalSex** in my app, for this purposes I use `HealthKitReporter.characteristicsQuery()` method. 
I've faced with the following problem.
I get an exception `_TypeError (type 'Null' is not a subtype of type 'String')` in case if I request permissions only for `CharacteristicType.dateOfBirth` , `CharacteristicType.biologicalSex` and then call `HealthKitReporter.characteristicsQuery()`.
As result I have to request permissions for all characteristics and then call `HealthKitReporter.characteristicsQuery()` to get only **BirthDate** and **BiologicalSex**.
Is it possible to get these characteristics without requesting additional permissions?

**Comment by VictorKachalov** [comment]
Hi @AlexanderZgersky 

Thank you for the question and for using this package.

I tried to reproduce your issuem allowing only reading the DateOfBirth and BiologicalSex type. Within this case I received the folowwing response from the native code:

![Bildschirmfoto 2021-09-12 um 18 29 22](https://user-images.githubusercontent.com/29483640/132995381-53a73663-51f7-4bf1-8498-8d6ae97f6464.png)

According to the apple documentation:
<img width="487" alt="Bildschirmfoto 2021-09-12 um 18 29 12" src="https://user-images.githubusercontent.com/29483640/132995373-06e56b58-20c3-4e31-9e2e-bd7dfb9c2796.png">

So if there is no permission or data in the Health App, the "na" will be used for the value.

Please also be sure you use the latest version of the oroginal [HealthKitReporter iOS CocoaPod](https://github.com/VictorKachalov/HealthKitReporter)

**Comment by VictorKachalov** [comment]
Hi @AlexanderZgersky 

Thank you for your report and using this package.

Indeed, there is an issue with the parsing. I made a fix and published a new version 1.4.1

**Comment by AlexanderZgersky** [comment]
@VictorKachalov Thank you for your support, after upgrading to version 1.4.1, the problem disappeared.
