### ISSUE TITLE
1.5.x introduces API breaking changes

### ISSUE THREAD

**Issue by maltemedocs** [VictorKachalov/health_kit_reporter#33]
**Describe the bug**
Version 1.5.x is mislabeled. Its version number suggests that there are new features with no breaking API changes. But in fact old code is not compatible anymore.

**To Reproduce**

 1. Have a flutter project that relies on version 1.3.x or 1.4.x of this plugin.
 2. Run flutter clean, remove the pubspec.lock
 2. Run flutter pub upgrade
 3. See error messages

**Expected behavior**
The plugin should continue to work with the old code, as it's a minor series upgrade. What is now called 1.5.x should have been a 2.x

**Screenshots**
None, but changes like https://github.com/VictorKachalov/health_kit_reporter/commit/f08e62901555af0d859ec829bbc682a73ee9d38c#diff-bb8f6fdce8b91b43f4156f21e5fed48f710f08ebaad88347e4b3cc896fdccd6dR167 are likely to have caused the problem.

**Desktop (please complete the following information):**
All of them

**Smartphone (please complete the following information):**
All of them

**Additional context**
Please see https://dart.dev/tools/pub/versioning

**Comment by VictorKachalov** [comment]
Hi @maltemedocs 

thank you, makes sense, I will soon publish version 2.0.0 with some other breaking changes.
