### ISSUE TITLE
request isAuthorizedToRead

### ISSUE THREAD

**Issue by takapiroid88** [VictorKachalov/health_kit_reporter#35]
I'd like to check is authorized to read.

isAuthorizedToWrite is exists, but not for read.

before request to read access, check is authorized to read.

can you help me?

**Comment by VictorKachalov** [comment]
Hi @takapiroid88 

As it stands in the [documentation](https://developer.apple.com/documentation/healthkit/authorizing_access_to_health_data) here:

"To help protect the user’s privacy, your app doesn’t know whether the user granted or denied permission to read data from HealthKit. If the user denied permission, attempts to query data from HealthKit return only samples that your app successfully saved to the HealthKit store."

By native tools in official way you are not able to get this information.
