### ISSUE TITLE
Adding Blood Pressure Correlation Crashes

### ISSUE THREAD

**Issue by adiltirur** [VictorKachalov/health_kit_reporter#44]
I am trying to write Blood Pressure value both Systolic and Diastolic as a Correlation but the app crashes. 

        final sysVal = QuantityHarmonized(120, 'mmHg', null);
        final diaVal = QuantityHarmonized(89, 'mmHg', null);

        final sys = Quantity(
            'testSysUUID234',
            QuantityType.bloodPressureSystolic.identifier,
            minuteAgo.millisecondsSinceEpoch,
            now.millisecondsSinceEpoch,
            device,
            sourceRevision,
            sysVal);
        final dia = Quantity(
            'testDiaUUID456',
            QuantityType.bloodPressureDiastolic.identifier,
            minuteAgo.millisecondsSinceEpoch,
            now.millisecondsSinceEpoch,
            device,
            sourceRevision,
            diaVal);
            final bpVal = CorrelationHarmonized([sys, dia], [], null);
            final bp = Correlation(
                             'testSysUUID456',
                             CorrelationType.bloodPressure.identifier,
                             minuteAgo.millisecondsSinceEpoch,
                             now.millisecondsSinceEpoch,
                             device,
                             sourceRevision,
                            bpVal);
         final savedBP = await HealthKitReporter.save(bp);

Here is my Code. Is there something wrong or the plugin doesn't support adding blood pressure yet?

I don't want to add the as separate Quantity because then it won't show up in the health app

Can someone help me please?

**Comment by VictorKachalov** [comment]
please check out version 2.0.4

**Comment by adiltirur** [comment]
Perfect, Works like a charm!

Thanks a ton,
