### ISSUE TITLE
Build error with latest version

### ISSUE THREAD

**Issue by nohli** [VictorKachalov/health_kit_reporter#45]
**Describe the bug**
`'Correlation' has no member 'make'`:

```
    /Users/builder/programs/flutter_3_0_1/.pub-cache/hosted/pub.dartlang.org/health_kit_reporter-2.0.4/ios/Classes/Extensions+SwiftHealthKitReporterPlugin.swift:1482:42: error: type 'Correlation' has no member 'make'
                let sample = try Correlation.make(from: correlation)
                                 ~~~~~~~~~~~ ^~~~
    Command CompileSwiftSources failed with a nonzero exit code
```

**To Reproduce**
1. Add plugin version 2.0.4 to app
2. Build app for iOS

**Expected behavior**
Build succeeds

**Desktop (please complete the following information):**
 - Flutter 3.0.1

**Additional context**
Build log is from Codemagic.

**Comment by VictorKachalov** [comment]
Hi @nohli 

Please try to update via "pod update" the original HealthKitReportor cocoapod
