### ISSUE TITLE
Unexpected dataType of class HKActivitySummaryType for startDate predicate

### ISSUE THREAD

**Issue by DmitriyGavrilov** [VictorKachalov/health_kit_reporter#6]
**Describe the bug**
I have this error:
` "Unexpected dataType of class HKActivitySummaryType for startDate predicate"`

`2020-12-23 14:19:03.814970+0300 Runner[5703:578480] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unexpected dataType of class HKActivitySummaryType for startDate predicate'
*** First throw call stack:
(0x1bce75344 0x1bcb8acc0 0x1bcd6551c 0x1d0bcbfa8 0x1d0b2005c 0x1d0b1fec8 0x1d0b1fb94 0x1d0aeb2d0 0x1d0ae89c4 0x1d0b08824 0x1049fb9c0 0x1049fb930 0x1049fb45c 0x104b974d8 0x104b97970 0x104b9212c 0x104b97a2c 0x104b97b2c 0x1032a1c84 0x102a603b4 0x102d3ac18 0x102a69948 0x102a6c074 0x1bcdf13a8 0x1bcdf10c0 0x1bcdf0740 0x1bcdeb538 0x1bcdeabc8 0x1c71cc5cc 0x1c0f9d744 0x1026c1b48 0x1bcc67384)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unexpected dataType of class HKActivitySummaryType for startDate predicate'
terminating with uncaught exception of type NSException
(lldb)
`

**Smartphone:**
 - Device:  iPhone11
 - OS: iOS13.6.1 

Please help.

**Comment by VictorKachalov** [comment]
Thank you, 

Have provided a fix, please review version 1.0.6

**Comment by DmitriyGavrilov** [comment]
Ok, now everything works fine, thank you very much!
